name: "Events"
output: "/vols/cms/sdb15/database_outputs/"
variations:
    - ["jesTotal", -2.]
    - ["jesTotal", -1.]
    - ["jesTotal", -0.5]
    - ["jesTotal", 0]
    - ["jesTotal", 0.5]
    - ["jesTotal", 1.]
    - ["jesTotal", 2.]
attributes:
    Both:
        run: "ev, source, nsig: ev.run"
        luminosityBlock: "ev, source, nsig: ev.luminosityBlock"
        event: "ev, source, nsig: ev.event"
        isdata: "ev, source, nsig: np.full(ev.size, ev.config.dataset.isdata, dtype=np.bool8)"
        parent: "ev, source, nsig: np.full(ev.size, ev.config.dataset.parent)"
        sample: "ev, source, nsig: np.full(ev.size, ev.config.dataset.name)"
        METnoX_pt: "ev, source, nsig: ev.METnoX_pt(ev, source, nsig)"
        METnoX_phi: "ev, source, nsig: ev.METnoX_phi(ev, source, nsig)"
        MET_pt: "ev, source, nsig: ev.MET_ptShift(ev, source, nsig)"
        MET_phi: "ev, source, nsig: ev.MET_phiShift(ev, source, nsig)"
        CaloMET_pt: "ev, source, nsig: ev.CaloMET_pt"
        CaloMET_phi: "ev, source, nsig: ev.CaloMET_phi"
        MET_dCaloMET: "ev, source, nsig: ev.MET_dCaloMET(ev, source, nsig)"
        MinDPhiJ1234METnoX: "ev, source, nsig: ev.MinDPhiJ1234METnoX(ev, source, nsig)"
        MTW: "ev, source, nsig: ev.MTW(ev, source, nsig)"
        MLL: "ev, source, nsig: ev.MLL(ev, source, nsig)"
        nJetVeto: "ev, source, nsig: ev.JetVeto(ev, source, nsig, 'eta').counts"
        nJetSelection: "ev, source, nsig: ev.JetSelection(ev, source, nsig, 'eta').counts"
        LeadJetSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'ptShift'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'eta'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'phi'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_chEmEF: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'chEmEF'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_chHEF: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'chHEF'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_neEmEF: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'neEmEF'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_neHEF: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'neHEF'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetSelection_dphiMET: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.JetSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadJetFwdSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetFwdSelection(ev, source, nsig, 'pt'), ev.JetFwdSelection(ev, source, nsig, 'pt'), 0, ev.size)"
        LeadJetFwdSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetFwdSelection(ev, source, nsig, 'eta'), ev.JetFwdSelection(ev, source, nsig, 'pt'), 0, ev.size)"
        LeadJetFwdSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetFwdSelection(ev, source, nsig, 'phi'), ev.JetFwdSelection(ev, source, nsig, 'pt'), 0, ev.size)"
        LeadJetFwdSelection_dphiMET: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetFwdSelection(ev, source, nsig, 'dphiMET'), ev.JetFwdSelection(ev, source, nsig, 'pt'), 0, ev.size)"
        NearestJetSelectionMET_pt: "ev, source, nsig: get_attr_for_min_ref(ev.JetSelection(ev, source, nsig, 'ptShift'), ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.size)"
        NearestJetSelectionMET_eta: "ev, source, nsig: get_attr_for_min_ref(ev.JetSelection(ev, source, nsig, 'eta'), ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.size)"
        NearestJetSelectionMET_phi: "ev, source, nsig: get_attr_for_min_ref(ev.JetSelection(ev, source, nsig, 'phi'), ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.size)"
        NearestJetSelectionMET_dphiMET: "ev, source, nsig: get_attr_for_min_ref(ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.size)"
        SecondJetSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'ptShift'), ev.JetSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondJetSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'eta'), ev.JetSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondJetSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'phi'), ev.JetSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondJetSelection_dphiMET: "ev, source, nsig: get_nth_sorted_object_indices(ev.JetSelection(ev, source, nsig, 'dphiMET'), ev.JetSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        nMuonVeto: "ev, source, nsig: ev.MuonVeto(ev, source, nsig, 'eta').counts"
        nMuonSelection: "ev, source, nsig: ev.MuonSelection(ev, source, nsig, 'eta').counts"
        LeadMuonSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'ptShift'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadMuonSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'eta'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadMuonSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'phi'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        SecondMuonSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'ptShift'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondMuonSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'eta'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondMuonSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.MuonSelection(ev, source, nsig, 'phi'), ev.MuonSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        nElectronVeto: "ev, source, nsig: ev.ElectronVeto(ev, source, nsig, 'eta').counts"
        nElectronSelection: "ev, source, nsig: ev.ElectronSelection(ev, source, nsig, 'eta').counts"
        LeadElectronSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'ptShift'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadElectronSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'eta'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadElectronSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'phi'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        SecondElectronSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'ptShift'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondElectronSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'eta'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        SecondElectronSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.ElectronSelection(ev, source, nsig, 'phi'), ev.ElectronSelection(ev, source, nsig, 'ptShift'), 1, ev.size)"
        nTauVeto: "ev, source, nsig: ev.TauVeto(ev, source, nsig, 'eta').counts"
        nTauSelection: "ev, source, nsig: ev.TauSelection(ev, source, nsig, 'eta').counts"
        LeadTauSelection_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.TauSelection(ev, source, nsig, 'ptShift'), ev.TauSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadTauSelection_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.TauSelection(ev, source, nsig, 'eta'), ev.TauSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadTauSelection_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.TauSelection(ev, source, nsig, 'phi'), ev.TauSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        LeadTauSelection_dphiMET: "ev, source, nsig: get_nth_sorted_object_indices(ev.TauSelection(ev, source, nsig, 'dphiMET'), ev.TauSelection(ev, source, nsig, 'ptShift'), 0, ev.size)"
        nPhotonVeto: "ev, source, nsig: ev.PhotonVeto(ev, source, nsig, 'eta').counts"
        nPhotonSelection: "ev, source, nsig: ev.PhotonSelection(ev, source, nsig, 'eta').counts"
        nBJetVeto: "ev, source, nsig: ev.JetBVeto(ev, source, nsig, 'eta').counts"
        PV_npvsGood: "ev, source, nsig: ev.PV_npvsGood"
        LeptonCharge: "ev, source, nsig: ev.LeptonCharge(ev, source, nsig)"
        IsMETTriggered: "ev, source, nsig: ev.IsMETTriggered(ev)"
        IsSingleMuonTriggered: "ev, source, nsig: ev.IsSingleMuonTriggered(ev)"
        IsSingleElectronTriggered: "ev, source, nsig: ev.IsSingleElectronTriggered(ev)"
        Flag_goodVertices: "ev, source, nsig: ev.Flag_goodVertices"
        Flag_globalSuperTightHalo2016Filter: "ev, source, nsig: ev.Flag_globalSuperTightHalo2016Filter"
        Flag_HBHENoiseFilter: "ev, source, nsig: ev.Flag_HBHENoiseFilter"
        Flag_HBHENoiseIsoFilter: "ev, source, nsig: ev.Flag_HBHENoiseIsoFilter"
        Flag_EcalDeadCellTriggerPrimitiveFilter: "ev, source, nsig: ev.Flag_EcalDeadCellTriggerPrimitiveFilter"
        Flag_BadPFMuonFilter: "ev, source, nsig: ev.Flag_BadPFMuonFilter"
        Flag_BadGlobalMuon: "ev, source, nsig: ev.Flag_BadGlobalMuon"
        Flag_CloneGlobalMuon: "ev, source, nsig: ev.Flag_CloneGlobalMuon"
        Flag_eeBadScFilter: "ev, source, nsig: ev.Flag_eeBadScFilter"
    MC:
        nGenBosonSelection: "ev, source, nsig: ev.nGenBosons(ev)"
        GenPartBoson_pt: "ev, source, nsig: ev.GenPartBoson(ev, 'pt')"
        GenPartBoson_eta: "ev, source, nsig: ev.GenPartBoson(ev, 'eta')"
        GenPartBoson_phi: "ev, source, nsig: ev.GenPartBoson(ev, 'phi')"
        GenPartBoson_mass: "ev, source, nsig: ev.GenPartBoson(ev, 'mass')"
        LeadGenLepCandidate_pdgId: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'pdgId'), ev.GenLepCandidates(ev, 'pt'), 0, ev.size)"
        LeadGenLepCandidate_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'pt'), ev.GenLepCandidates(ev, 'pt'), 0, ev.size)"
        LeadGenLepCandidate_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'eta'), ev.GenLepCandidates(ev, 'pt'), 0, ev.size)"
        LeadGenLepCandidate_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'phi'), ev.GenLepCandidates(ev, 'pt'), 0, ev.size)"
        LeadGenLepCandidate_mass: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'mass'), ev.GenLepCandidates(ev, 'pt'), 0, ev.size)"
        SecondGenLepCandidate_pdgId: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'pdgId'), ev.GenLepCandidates(ev, 'pt'), 1, ev.size)"
        SecondGenLepCandidate_pt: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'pt'), ev.GenLepCandidates(ev, 'pt'), 1, ev.size)"
        SecondGenLepCandidate_eta: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'eta'), ev.GenLepCandidates(ev, 'pt'), 1, ev.size)"
        SecondGenLepCandidate_phi: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'phi'), ev.GenLepCandidates(ev, 'pt'), 1, ev.size)"
        SecondGenLepCandidate_mass: "ev, source, nsig: get_nth_sorted_object_indices(ev.GenLepCandidates(ev, 'mass'), ev.GenLepCandidates(ev, 'pt'), 1, ev.size)"
        LeptonIsElectron: "ev, source, nsig: ev.LeptonIs(ev, 'Electron')"
        LeptonIsMuon: "ev, source, nsig: ev.LeptonIs(ev, 'Muon')"
        LeptonIsTau: "ev, source, nsig: ev.LeptonIs(ev, 'Tau')"
        nGenTauL: "ev, source, nsig: ev.nGenTauL(ev)"
        WeightXsLumi: "ev, source, nsig: ev.WeightXsLumi(ev)"
        WeightQcdEwk: "ev, source, nsig: ev.WeightQcdEwk(ev, source, nsig)"
        WeightPU: "ev, source, nsig: ev.WeightPU(ev, source, nsig)"
        WeightPreFiring: "ev, source, nsig: ev.WeightPreFiring(ev, source, nsig)"
        WeightMETTrig: "ev, source, nsig: ev.WeightMETTrig(ev, source, nsig)"
        WeightSingleMuonTrig: "ev, source, nsig: 1-jagged_prod(1-ev.MuonSelection(ev, source, nsig, 'WeightmuonTrigSF'))"
        WeightSingleElectronTrig: "ev, source, nsig: 1-jagged_prod(1-ev.ElectronSelection(ev, source, nsig, 'WeighteleTrigSF'))"
        WeightOneMinusElectronVetoNoSelectionIdIsoVeto: "ev, source, nsig: jagged_prod(1-ev.ElectronVetoNoSelection(ev, source, nsig, 'WeighteleIdIsoVetoSF'))"
        WeightOneMinusElectronSelectionIdIsoTight: "ev, source, nsig: jagged_prod(1-ev.ElectronSelection(ev, source, nsig, 'WeighteleIdIsoTightSF'))"
        WeightOneMinusElectronVetoReco: "ev, source, nsig: jagged_prod(1-ev.ElectronVeto(ev, source, nsig, 'WeighteleRecoSF'))"
        WeightOneMinusElectronVetoNoSelectionReco: "ev, source, nsig: jagged_prod(1-ev.ElectronVetoNoSelection(ev, source, nsig, 'WeighteleRecoSF'))"
        WeightOneMinusMuonVetoNoSelectionIdLoose: "ev, source, nsig: jagged_prod(1-ev.MuonVetoNoSelection(ev, source, nsig, 'WeightmuonIdLooseSF'))"
        WeightOneMinusMuonVetoNoSelectionIsoLoose: "ev, source, nsig: jagged_prod(1-ev.MuonVetoNoSelection(ev, source, nsig, 'WeightmuonIsoLooseSF'))"
        WeightOneMinusMuonSelectionIdTight: "ev, source, nsig: jagged_prod(1-ev.MuonSelection(ev, source, nsig, 'WeightmuonIdTightSF'))"
        WeightOneMinusMuonSelectionIsoTight: "ev, source, nsig: jagged_prod(1-ev.MuonSelection(ev, source, nsig, 'WeightmuonIsoTightSF'))"
        WeightOneMinusPhotonVetoIdLoose: "ev, source, nsig: jagged_prod(1-ev.PhotonVeto(ev, source, nsig, 'WeightphotonIdLooseSF'))"
        WeightOneMinusPhotonVetoPixelSeedVeto: "ev, source, nsig: jagged_prod(1-ev.PhotonVeto(ev, source, nsig, 'WeightphotonPixelSeedVetoSF'))"
        WeightOneMinusTauSelectionIdTight: "ev, source, nsig: jagged_prod(1-ev.TauSelection(ev, source, nsig, 'WeighttauIdTightSF'))"
        WeightOneMinusJetBVetoIdMedium: "ev, source, nsig: jagged_prod(1-ev.JetBVeto(ev, source, nsig, 'btagSF'))"
        WeightMuonSelectionIdTight: "ev, source, nsig: jagged_prod(ev.MuonSelection(ev, source, nsig, 'WeightmuonIdTightSF'))"
        WeightMuonSelectionIsoTight: "ev, source, nsig: jagged_prod(ev.MuonSelection(ev, source, nsig, 'WeightmuonIsoTightSF'))"
        WeightTauSelectionIdTight: "ev, source, nsig: jagged_prod(ev.TauSelection(ev, source, nsig, 'WeighttauIdTightSF'))"
        WeightElectronSelectionIdIsoTight: "ev, source, nsig: jagged_prod(ev.ElectronSelection(ev, source, nsig, 'WeighteleIdIsoTightSF'))"
        WeightElectronSelectionReco: "ev, source, nsig: jagged_prod(ev.ElectronSelection(ev, source, nsig, 'WeighteleRecoSF'))"
        Generator_id1: "ev, source, nsig: ev.Generator_id1"
        Generator_id2: "ev, source, nsig: ev.Generator_id2"
        Generator_x1: "ev, source, nsig: ev.Generator_x1"
        Generator_x2: "ev, source, nsig: ev.Generator_x2"
    Data:
        IsCertified: "ev, source, nsig: ev.IsCertified(ev)"
dtypes:
    run: "int64"
    luminosityBlock: "int64"
    event: "int64"
    isdata: "bool"
    parent: "str"
    sample: "str"
    METnoX_pt: "float64"
    METnoX_phi: "float64"
    MET_pt: "float64"
    MET_phi: "float64"
    CaloMET_pt: "float64"
    CaloMET_phi: "float64"
    MET_dCaloMET: "float64"
    MinDPhiJ1234METnoX: "float64"
    MTW: "float64"
    MLL: "float64"
    nJetVeto: "int64"
    nJetSelection: "int64"
    LeadJetSelection_pt: "float64"
    LeadJetSelection_eta: "float64"
    LeadJetSelection_phi: "float64"
    LeadJetSelection_chEmEF: "float64"
    LeadJetSelection_chHEF: "float64"
    LeadJetSelection_neEmEF: "float64"
    LeadJetSelection_neHEF: "float64"
    LeadJetSelection_dphiMET: "float64"
    LeadJetFwdSelection_pt: "float64"
    LeadJetFwdSelection_eta: "float64"
    LeadJetFwdSelection_phi: "float64"
    LeadJetFwdSelection_dphiMET: "float64"
    NearestJetSelectionMET_pt: "float64"
    NearestJetSelectionMET_eta: "float64"
    NearestJetSelectionMET_phi: "float64"
    NearestJetSelectionMET_dphiMET: "float64"
    SecondJetSelection_pt: "float64"
    SecondJetSelection_eta: "float64"
    SecondJetSelection_phi: "float64"
    SecondJetSelection_dphiMET: "float64"
    nMuonVeto: "int64"
    nMuonSelection: "int64"
    LeadMuonSelection_pt: "float64"
    LeadMuonSelection_eta: "float64"
    LeadMuonSelection_phi: "float64"
    SecondMuonSelection_pt: "float64"
    SecondMuonSelection_eta: "float64"
    SecondMuonSelection_phi: "float64"
    nElectronVeto: "int64"
    nElectronSelection: "int64"
    LeadElectronSelection_pt: "float64"
    LeadElectronSelection_eta: "float64"
    LeadElectronSelection_phi: "float64"
    SecondElectronSelection_pt: "float64"
    SecondElectronSelection_eta: "float64"
    SecondElectronSelection_phi: "float64"
    nTauVeto: "int64"
    nTauSelection: "int64"
    LeadTauSelection_pt: "float64"
    LeadTauSelection_eta: "float64"
    LeadTauSelection_phi: "float64"
    LeadTauSelection_dphiMET: "float64"
    nPhotonVeto: "int64"
    nPhotonSelection: "int64"
    nBJetVeto: "int64"
    PV_npvsGood: "int64"
    LeptonCharge: "int64"
    IsMETTriggered: "bool"
    IsSingleMuonTriggered: "bool"
    IsSingleElectronTriggered: "bool"
    Flag_goodVertices: "bool"
    Flag_globalSuperTightHalo2016Filter: "bool"
    Flag_HBHENoiseFilter: "bool"
    Flag_HBHENoiseIsoFilter: "bool"
    Flag_EcalDeadCellTriggerPrimitiveFilter: "bool"
    Flag_BadPFMuonFilter: "bool"
    Flag_BadGlobalMuon: "bool"
    Flag_CloneGlobalMuon: "bool"
    Flag_eeBadScFilter: "bool"
    nGenBosonSelection: "int64"
    GenPartBoson_pt: "float64"
    GenPartBoson_eta: "float64"
    GenPartBoson_phi: "float64"
    GenPartBoson_mass: "float64"
    LeadGenLepCandidate_pdgId: "float64"
    LeadGenLepCandidate_pt: "float64"
    LeadGenLepCandidate_eta: "float64"
    LeadGenLepCandidate_phi: "float64"
    LeadGenLepCandidate_mass: "float64"
    SecondGenLepCandidate_pdgId: "float64"
    SecondGenLepCandidate_pt: "float64"
    SecondGenLepCandidate_eta: "float64"
    SecondGenLepCandidate_phi: "float64"
    SecondGenLepCandidate_mass: "float64"
    LeptonIsElectron: "bool"
    LeptonIsMuon: "bool"
    LeptonIsTau: "bool"
    nGenTauL: "int64"
    WeightXsLumi: "float64"
    WeightQcdEwk: "float64"
    WeightPU: "float64"
    WeightPreFiring: "float64"
    WeightMETTrig: "float64"
    WeightSingleMuonTrig: "float64"
    WeightSingleElectronTrig: "float64"
    WeightOneMinusElectronVetoNoSelectionIdIsoVeto: "float64"
    WeightOneMinusElectronSelectionIdIsoTight: "float64"
    WeightOneMinusElectronVetoReco: "float64"
    WeightOneMinusElectronVetoNoSelectionReco: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose: "float64"
    WeightOneMinusMuonSelectionIdTight: "float64"
    WeightOneMinusMuonSelectionIsoTight: "float64"
    WeightOneMinusPhotonVetoIdLoose: "float64"
    WeightOneMinusPhotonVetoPixelSeedVeto: "float64"
    WeightOneMinusTauSelectionIdTight: "float64"
    WeightOneMinusJetBVetoIdMedium: "float64"
    WeightMuonSelectionIdTight: "float64"
    WeightMuonSelectionIsoTight: "float64"
    WeightTauSelectionIdTight: "float64"
    WeightElectronSelectionIdIsoTight: "float64"
    WeightElectronSelectionReco: "float64"
    Generator_id1: "int64"
    Generator_id2: "int64"
    Generator_x1: "float64"
    Generator_x2: "float64"
    IsCertified: "bool"
