variable: "variable0"
binning: "bin0=[100,120,140,160,180,200,220,240,260,280,300,340,380,420,500,600,800,1000]"
selections:
    met_trigger: "True"
shape: True
regions:
    - "singlemu"
    - "doublemu"
    - "triplemu"
processes:
    singlemu_pass: 1
    doublemu_pass: 2
    triplemu_pass: 3
conversions:
    singlemu_tot:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "SingleMuon_noMETTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "singlemu", "data_obs"]]
    doublemu_tot:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "DoubleMuon_noMETTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "doublemu", "data_obs"]]
    triplemu_tot:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "TripleMuon_noMETTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "triplemu", "data_obs"]]
    singlemu_pass:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "SingleMuon_METTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "singlemu", "singlemu_pass"]]
    doublemu_pass:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "DoubleMuon_METTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "doublemu", "doublemu_pass"]]
    triplemu_pass:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleMuon", "TripleMuon_METTrigger", "SingleMuon"]]
        new_labels: [["SingleMuon", "triplemu", "triplemu_pass"]]
parameters: []
systematics: []
