variable: "variable0"
binning: "bin0=[71,111]"
selections:
    mll_shape: "True"
shape: True
regions:
    - "None"
processes:
    dyll: 1
    gll:  2
    zll:  3
conversions:
    dyll:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "None", "DYJetsToLL"]]
        new_labels: [["MET", "none", "dyll"]]
    gll:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "None", "GStarJetsToLL"]]
        new_labels: [["MET", "none", "gll"]]
    zll:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "None", "ZJetsToLL"]]
        new_labels: [["MET", "none", "zll"]]
parameters:
    - ["*", "autoMCStats", "10", "1"]
systematics:
    - "lhePdf"
    - "lheScale"
